services:
  pg:
    restart: unless-stopped
    container_name: pg_db2
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dv8
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data2:/var/lib/postgresql/data
    networks:
      cloud_manager:
        ipv4_address: 173.23.0.9
  # server:
  #   image: example-api:latest
  #   restart: unless-stopped
  #   container_name: server-app2
  #   depends_on:
  #     - pg
  #   environment:
  #     - DB_HOST=173.23.0.9
  #     - DB_PORT=5432
  #     - DB_NAME=employees
  #     - DB_USER=root
  #     - DB_PASSWORD=password
  #   ports:
  #     - 8000:80
  #   networks:
  #     cloud_manager:
  #       ipv4_address: 173.23.0.5

  # client:
  #   image: example-client:latest
  #   restart: unless-stopped
  #   container_name: client-app2
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_API_URL=http://localhost:8000/api/v1
  #   depends_on:
  #     - server
  #   ports:
  #     - 3000:3000
  #   networks:
  #     cloud_manager:
  #       ipv4_address: 173.23.0.3

networks:
  cloud_manager:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.23.0.0/24
          gateway: 173.23.0.1

volumes:
  pg_data2:
